---
title: "Arrays"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error=TRUE,collapse = T)
library(reticulate)

```

<style>
div.python pre { background-color: #e9f7f5
; }
</style>

<style>
div.r pre { background-color: #fff5fd; }
</style>


This chapter delves deeper into the concepts of arrays and vectors that were introduced in the 'Basics' chapter. In Python, the primary package for working with arrays is numpy. The main advantage of using vectors is that it allows for vectorized operations, rather than using loops to perform operations on each element of an object. Vectorized operations allow for more efficient processing of blocks of data.



<p>&nbsp;</p>
<p>&nbsp;</p>

Let's first take a look at an example to understand the benefits of using vectorized operations:

<div class = "row">
<div class = "python">

```{python}
# Python 

import numpy as np
import time 

arr = np.arange(2000000)

lst = list(range(2000000))

t = time.time()
arr_2 = arr*2
time.time() - t

t = time.time()
lst_2 = [i*2  for i in lst]
time.time() - t


```

</div>
</div>


# Create arrays 

The NumPy library contains multidimensional array and matrix data structures and provides methods to efficiently operate on them. If you do not have numpy installed on your computer, you can install it by running ```pip install numpy``` in a terminal.

To use numpy, you need to load the module by running ```import numpy as np```. This allows you to refer to numpy as "np" throughout your code, which keeps it standardized.

Numpy allows for fast and efficient calculations. The main difference between Numpy and python lists is that all elements in a numpy array must be homogeneous and numpy uses less memory to store data.

Functions | Tasks
-|-:
array	| Create numpy array
ndim |	Dimension of the array
shape	| Size of the array (Number of rows and Columns)
size	| Total number of elements in the array
dtype	| Type of elements in the array, i.e., int64, character
reshape	| Reshapes the array without changing the original shape
resize	| Reshapes the array. Also change the original shape
arange	| Create sequence of numbers in array
Itemsize	| Size in bytes of each item
diag	| Create a diagonal matrix
vstack	| Stacking vertically
hstack	| Stacking horizontally

- Starting from existing list or vector :

<div class = "row">
<div class = "python">

```{python}
# Python 

import numpy as np

arr = np.array([1, 2, 3, 4])
arr

```

</div>
</div>

- Create arrays with zero, one, sequence..


<div class = "row">
<div class = "python">

```{python}
# Python 

np.zeros([2, 3])


np.ones((2, 3))


np.arange(1, 7)


np.arange(1, 7).reshape(2, 3)

## remember from first chapter that array in R and Python aren't store the same way, set order = 'F' to get the same results


np.arange(1, 7).reshape([2, 3], order = 'F')

np.linspace(1, 4,num = 10)
```

</div>
</div>

## Random array 


<div class = "row">
<div class = "python">

```{python}
# Python 

#generate an array
arr_rd = np.random.randn(4,5)

arr_rd

```

</div>
</div>

## Indexing and slicing

<div class = "row">
<div class = "python">

```{python}
# Python 

arr = np.arange(1,7).reshape(2,3)
arr[0]
arr[:2]
arr[1:]
```

</div>
</div>
## Shape and size
    


<div class = "row">
<div class = "python">

```{python}
# Python 

# .ndim gives the number of axes, or dimensions, of the array.
arr_rd.ndim
```

```{python}
# Python 

# .size gives the total number of elements of the array. 
arr_rd.size

```

```{python}
# Python 

# .shape display a tuple of integers with the number of elements stored along each dimension of the array
arr_rd.shape
```

</div>
</div>

# Modifiying arrays

## Add elements 

<div class = "row">
<div class = "python">

```{python}
# Python 
arr

# /!\ using append it convert the array to a 1d array
arr_1d = np.append(arr, [7, 8, 9])
arr_1d

# using insert you can add rows and columns 
np.insert(arr, len(arr), [7, 8, 9], axis = 0)

np.insert(arr, 2, [7, 8], axis = 1)

```

</div>
</div>

- Combining/splitting arrays

<div class = "row">
<div class = "python">

```{python}
# Python 
arr0 = np.zeros([2,3])
arr1 = np.ones([2,3])

arr01 = np.vstack([arr0,arr1])
arr01

#or 
np.concatenate([arr0,arr1], axis = 0)

np.hstack([arr0,arr1])

#or
np.concatenate([arr0,arr1], axis = 1)

np.hsplit(arr01,3)
np.vsplit(arr01,4)

```

</div>
</div>




## Delete elements


<div class = "row">
<div class = "python">

```{python}
# Python 

np.delete(arr,1 , axis = 1)

np.delete(arr,1 , axis = 0)

```

</div>
</div>

## Sorting


<div class = "row">
<div class = "python">

```{python}
# Python 

arr = np.random.randn(10)

arr
arr.sort()


```

```{python}
# Python 

arr = np.random.randn(4,3)

arr
arr.sort(1)


```

</div>
</div>

# Conditional Logic on array

Imagine you have two square matrices representing interactions between entities. Each matrix represents a basic network, with a value of 1 indicating interaction and 0 indicating no interaction. You want to determine if two entities that are linked in one network are also linked in another network. Instead of checking each entity's interaction sequentially in a loop, you can use matrix operations to perform element-wise calculations and get the same result in a more efficient manner.

<div class = "row">
<div class = "python">

```{python}
# Python 

#generate a list
list_1 = [[0,1,0,1],[1,0,1,0],[0,1,0,1],[1,0,1,0]]
network_1 = np.array(list_1)

#generate a sequence
list_2 = [[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]]
network_2 = np.array(list_2)

network_12 = network_1*network_2
network_12
```

</div>
</div>

## Select specific elements


<div class = "row">
<div class = "python">

```{python}
# Python 

network_12 > 0

network_12[network_12>0]
```

</div>
</div>


One thing that is commonly needed is to modify specific values in an array that meet a certain condition. The first step is to identify which cells meet the condition. In Python, the function `np.where` is commonly used.



It is important to note that the execution time can change depending on the size of the vector.

<div class = "row">
<div class = "python">

```{python}
# Python 

arr = np.arange(200000)


t = time.time()
results = [(i if i%2==0 else 0) for i in arr]
time.time() - t


t = time.time()
results = np.where(arr%2!=0,0,arr)
time.time() - t
```

```{python}
# Python 

arr = np.arange(20000000)


t = time.time()
results = [(i if i%2==0 else 0) for i in arr]
time.time() - t


t = time.time()
results = np.where(arr%2!=0,0,arr)
time.time() - t
```

</div>
</div>




# Algebra

<div class = "row">
<div class = "python">

```{python}
# Python 
from numpy.linalg import inv, qr 
 
X = np.array([[0,1,5,1],[2,1,3,1],[2,1,9,6],[7,2,1,0],[8,3,5,5]]) 
Y = np.array([0,1,2,5,4])

X
X.T.dot(X) 
# same as 
XtX = np.dot(X.T,X)
# same as 
X.T @ X

# inverse Matrix
inv(XtX)


```

```{python}
# Python 

XtY = np.dot(X.T,Y)

# OLS 
Beta = inv(XtX).dot(XtY)
Beta
```

</div>
</div>


# Operation on array

Operator	| Equivalent |Description
-|:-:|-:
+	| np.add	| Addition (e.g., 1 + 1 = 2)
-	| np.subtract	| Subtraction (e.g., 3 - 2 = 1)
-	| np.negative |	Unary negation (e.g., -2)
*	| np.multiply	| Multiplication (e.g., 2 * 3 = 6)
/	| np.divide	| Division (e.g., 3 / 2 = 1.5)
// |	np.floor_divide	| Floor division (e.g., 3 // 2 = 1)
**	| np.power	| Exponentiation (e.g., 2 ** 3 = 8)
%	| np.mod | Modulus/remainder (e.g., 9 % 4 = 1)


<div class = "row">
<div class = "python">

```{python}
# Python 

network_12 = np.triu(network_12,1)

# nb of link
network_12.sum()
# same since there is only 0 and 1 
(network_12>0).sum()

# share of link 
network_12.mean()


# nb link by entities
network_12.sum(axis=1)

# share of link across entities (by columns)
network_12.mean(1)



```

</div>
</div>


## Map (Python)

In python we can use ```map``` to do the same thing than apply familly in R with a bit of manipulation.

```map```  takes different types of input and transforms it by row if the object is an array, returning an iterator. You can then transform this iterator into a list or an array.

<div class = "python">

```{python, collapse = TRUE}
# Python

arr_1 = np.arange(1,17).reshape([4,4], order = 'F')
arr_1


# by row, by columns you need to tranpose the array
map(np.sum,arr_1)
list(map(np.sum,arr_1))


# with a list
lst_1 = [arr_1,np.linspace(1,8,num=arr_1.size)]

list(map(lambda x: x**2,lst_1))

```

</div>

- Pandas' apply function:

When using pandas, you can also use apply functions. The difference between "apply" and "map" is that, by default, "apply" works on columns, because variables in a dataframe are stored by columns.

<div class = "python">

```{python, collapse = TRUE}
# Python

import pandas as pd

arr_1 = np.arange(1,17).reshape([4,4], order = 'F')

#transform the array into a DataFrame
df_1 = pd.DataFrame(arr_1)
df_1


# Apply the function by column
df_1.apply(sum)


```

</div>


# Exercises

</div>


<p>&nbsp;</p>
<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 1**

The series, $1^{1} + 2^{2} + 3^{3} + ... + 10^{10} = 10405071317$.

Find the last ten digits of the series, $1^{1} + 2^{2} + 3^{3} + ... + 1000^{1000}$.

</div>


<p>&nbsp;</p>
<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 2**

Try to vectorize exercices from chapter 1, you can also compare it with apply/map functions.

</div>


<p>&nbsp;</p>
<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">
 

**Exercise 3**

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

</div>


<p>&nbsp;</p>
<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 4**
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.


</div>


<p>&nbsp;</p>
<p>&nbsp;</p>


<a href="exo_chap_2.html">Solutions</a>

